### ISSUE TITLE
cudaTimer

### ISSUE THREAD

**Issue by wspt96** [Legion56/Counting-ICCV-DSSINet#5]
` logging.info("load/iter/cuda: {} vs {} vs {} seconds; iter: {}".format(load_time, iter_time, net.cudaTimer.tot_time, net.cudaTimer.calls))
        net.cudaTimer.tot_time = 0`
When I run the code , I meet a problem. it tell me 'CrowdCounter  object has no attribute cudaTimer '
And I can't find cudaTimer in your code or in nn.Module
So where can I find this attribute to fix the bug

**Comment by wspt96** [comment]
appreciate your reply

**Comment by chen-judge** [comment]
I just delete this code.

**Comment by wspt96** [comment]
thk you, another question, can you get the result showed in the paper? Like ShanghaiTech PartA

**Comment by wspt96** [comment]
> I just delete this code.

thk you, another question, can you get the result showed in the paper? Like ShanghaiTech PartA

**Comment by wspt96** [comment]
#network.load_net('../../pruned_VGG.h5', self.model.front_end, skip=True)
#network.load_net("../../vgg16.h5", self.model.front_end, skip=True)
sorry to bother again, I find your code lacks this two pretrained model, so can you release these two models?

**Comment by wspt96** [comment]
#network.load_net('../../pruned_VGG.h5', self.model.front_end, skip=True)
#network.load_net("../../vgg16.h5", self.model.front_end, skip=True)
sorry to bother again, I find your code lacks this two pretrained model, so can you release these two models? especially pruned_vgg.h5 file

**Comment by Legion56** [comment]
#3
